[weather]
WeatherToken = "OpenWeatherMap API Token"
# Default forecast city
City = "Moscow"

[news]
ApiKey = "Api key from Newsapi.org"
Country = "us"
Articles = 5

[translate]
ApiKey = "Yandex Translate API key"

[general]
GeonamesUsername = "Username from Geonames.org"
Language = "en"
# UTC 0 + Timezone
Timezone = 5
Game = "Half-Life 3"

[currency]
Default = ["USD", "EUR"]
